### ISSUE TITLE
[ISSUE] Failed to download library 'javax.inject:javax.inject:1'

### ISSUE THREAD

**Issue by LeStegii** [AlessioDP/libby#32]
When I try to load my dependency using the library loader, I get an error when it comes to downloading `javax.inject` which seems to be a transitive dependency. I also tried excluding the dependency, but this didn't work either.

- **javax.inject:** https://mvnrepository.com/artifact/javax.inject/javax.inject/1
- **libby version:** 2.0.0-SNAPSHOT (https://repo.alessiodp.com/#/snapshots/com/alessiodp/libby/libby-bukkit/2.0.0-SNAPSHOT)

![grafik](https://github.com/AlessioDP/libby/assets/50475262/89cb3a3d-a6c0-4125-9af6-2b7a6675ac6d)

```console
[14:13:16 ERROR]: [kLoader] Error initializing plugin 'kLoader-1.0.0-all.jar' in folder 'plugins' (Is it up to date?)
java.lang.RuntimeException: Failed to download library 'javax.inject:javax.inject:1'
	at net.kettlemc.kLoader.libs.com.alessiodp.libby.LibraryManager.downloadLibrary(LibraryManager.java:553) ~[kLoader-1.0.0-all.jar:?]
	at net.kettlemc.kLoader.libs.com.alessiodp.libby.transitive.TransitiveDependencyHelper.<init>(TransitiveDependencyHelper.java:64) ~[kLoader-1.0.0-all.jar:?]
	at net.kettlemc.kLoader.libs.com.alessiodp.libby.LibraryManager.resolveTransitiveLibraries(LibraryManager.java:615) ~[kLoader-1.0.0-all.jar:?]
	at net.kettlemc.kLoader.libs.com.alessiodp.libby.LibraryManager.loadLibrary(LibraryManager.java:640) ~[kLoader-1.0.0-all.jar:?]
	at net.kettlemc.kloader.loading.DependencyLoader.loadJaskl(DependencyLoader.java:15) ~[kLoader-1.0.0-all.jar:?]
	at net.kettlemc.kloader.KLoader.onLoad(KLoader.java:21) ~[kLoader-1.0.0-all.jar:?]
	at net.kettlemc.kloader.PluginLoader.onLoad(PluginLoader.java:13) ~[kLoader-1.0.0-all.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:522) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2042]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by AlessioDP** [comment]
I tested the same code and it works for me.

The snapshot deployed in the repository is not the latest one, I deployed an updated version, try again with the newer :)

```java
lib = Library.builder()
      .artifactId("jaskl-hocon")
      .groupId("io{}github{}almighty-satan{}jaskl")
      .version("1.4.1")
      .resolveTransitiveDependencies(true)
      .build();
```
