### ISSUE TITLE
PaperLibraryLoader error

### ISSUE THREAD

**Issue by ItsRainingHP** [AlessioDP/libby#35]
Error:

![image](https://github.com/AlessioDP/libby/assets/79205731/1df74ee9-50fd-4a39-857a-6fbe63e18827)

pom.xml
```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.itsrainingplex</groupId>
  <artifactId>JarLoader</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <name>JarLoader</name>

  <properties>
    <java.version>17</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <relocations>
                        <relocation>
                            <pattern>net.byteflux.libby</pattern>
                            <pattern>com.alessiodp.libby</pattern>
                            <shadedPattern>yourPackage.libs.com.alessiodp.libby</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>maven-snapshots</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.19.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.alessiodp.libby</groupId>
            <artifactId>libby-paper</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin-bundle</artifactId>
            <version>5.6.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
```
Main class
```package com.itsrainingplex.jarloader;

import com.alessiodp.libby.Library;
import com.alessiodp.libby.PaperLibraryManager;
import io.javalin.Javalin;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.Arrays;

public final class JarLoader extends JavaPlugin {

    @Override
    public void onEnable() {
        PaperLibraryManager paperLibraryManager = new PaperLibraryManager(this);
        Library lib = Library.builder()
                .groupId("io.javalin")
                .artifactId("javalin-bundle")
                .version("5.6.1")
                .build();
        Library lib2 = Library.builder()
                .groupId("com.fasterxml.jackson.core")
                .artifactId("jackson-core")
                .version("2.15.1")
                .build();
        Library lib3 = Library.builder()
                .groupId("com.fasterxml.jackson.core")
                .artifactId("jackson-databind")
                .version("2.15.1")
                .build();
        Library lib4 = Library.builder()
                .groupId("org.slf4j")
                .artifactId("slf4j-simple")
                .version("2.0.6")
                .build();
        paperLibraryManager.addMavenCentral();
        paperLibraryManager.loadLibrary(lib2);
        paperLibraryManager.loadLibrary(lib3);
        paperLibraryManager.loadLibrary(lib4);
        paperLibraryManager.loadLibrary(lib);

        try (Javalin server = Javalin.create()
                .get("/", ctx -> ctx.result("Hello World"))
                .start(7070)) {
            getLogger().warning("Loaded server.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}
```

**Comment by frengor** [comment]
You need to also resolve the transitive dependencies of Javalin:
```diff
 Library lib = Library.builder()
                 .groupId("io.javalin")
                 .artifactId("javalin-bundle")
                 .version("5.6.1")
+                .resolveTransitiveDependencies(true)
                 .build();
```

**Comment by ItsRainingHP** [comment]
> You need to also resolve the transitive dependencies of Javalin:
> 
> ```diff
>  Library lib = Library.builder()
>                  .groupId("io.javalin")
>                  .artifactId("javalin-bundle")
>                  .version("5.6.1")
> +                .resolveTransitiveDependencies(true)
>                  .build();
> ```

That does help resolve the dependencies but I am still failing to resolve the library and returning NoClassDefError:

```
package com.itsrainingplex.jarloader;

import com.alessiodp.libby.Library;
import com.alessiodp.libby.PaperLibraryManager;
import io.javalin.Javalin;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.Arrays;

public final class JarLoader extends JavaPlugin {

    @Override
    public void onEnable() {
        PaperLibraryManager paperLibraryManager = new PaperLibraryManager(this);
        Library lib = Library.builder()
                .groupId("io.javalin")
                .artifactId("javalin")
                .version("5.6.1")
                .resolveTransitiveDependencies(true)
                .build();
        paperLibraryManager.addMavenCentral();
        paperLibraryManager.loadLibrary(lib);

        try (Javalin server = Javalin.create()
                .get("/", ctx -> ctx.result("Hello World"))
                .start(7070)) {
            getLogger().warning("Loaded server.");
        } catch (Exception e) {
            getLogger().warning(Arrays.toString(e.getStackTrace()));
        }
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}

```

```
[08:26:51 INFO]: [JarLoader] Enabling JarLoader v1.0.0
[08:26:51 INFO]: [JarLoader] Loading library javalin
[08:26:51 ERROR]: [STDERR] [org.slf4j.helpers.Util] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[08:26:51 ERROR]: [STDERR] [org.slf4j.helpers.Util] SLF4J: Defaulting to no-operation (NOP) logger implementation
[08:26:51 ERROR]: [STDERR] [org.slf4j.helpers.Util] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[08:27:05 INFO]: [JarLoader] Loading library annotations
[08:27:05 INFO]: [JarLoader] Loading library slf4j-api
[08:27:05 INFO]: [JarLoader] Loading library slf4j-simple
[08:27:05 INFO]: [JarLoader] Loading library jetty-server
[08:27:05 INFO]: [JarLoader] Loading library jetty-jakarta-servlet-api
[08:27:05 INFO]: [JarLoader] Loading library jetty-http
[08:27:05 INFO]: [JarLoader] Loading library jetty-util
[08:27:05 INFO]: [JarLoader] Loading library jetty-io
[08:27:05 INFO]: [JarLoader] Loading library jetty-webapp
[08:27:05 INFO]: [JarLoader] Loading library jetty-servlet
[08:27:05 INFO]: [JarLoader] Loading library jetty-security
[08:27:05 INFO]: [JarLoader] Loading library jetty-xml
[08:27:05 INFO]: [JarLoader] Loading library websocket-jetty-server
[08:27:05 INFO]: [JarLoader] Loading library websocket-jetty-common
[08:27:05 INFO]: [JarLoader] Loading library websocket-core-common
[08:27:05 INFO]: [JarLoader] Loading library websocket-servlet
[08:27:05 INFO]: [JarLoader] Loading library websocket-core-server
[08:27:05 INFO]: [JarLoader] Loading library jetty-annotations
[08:27:05 INFO]: [JarLoader] Loading library jetty-plus
[08:27:05 INFO]: [JarLoader] Loading library jakarta.transaction-api
[08:27:05 INFO]: [JarLoader] Loading library jetty-jndi
[08:27:05 INFO]: [JarLoader] Loading library jakarta.annotation-api
[08:27:05 INFO]: [JarLoader] Loading library asm
[08:27:05 INFO]: [JarLoader] Loading library asm-commons
[08:27:05 INFO]: [JarLoader] Loading library asm-tree
[08:27:05 INFO]: [JarLoader] Loading library websocket-jetty-api
[08:27:05 INFO]: [JarLoader] Loading library jvmbrotli
[08:27:05 INFO]: [JarLoader] Loading library jvmbrotli-linux-x86-amd64
[08:27:05 INFO]: [JarLoader] Loading library brotli4j
[08:27:05 INFO]: [JarLoader] Loading library service
[08:27:05 INFO]: [JarLoader] Loading library native-linux-x86_64
[08:27:05 INFO]: [JarLoader] Loading library jackson-databind
[08:27:05 INFO]: [JarLoader] Loading library jackson-annotations
[08:27:05 INFO]: [JarLoader] Loading library jackson-core
[08:27:05 INFO]: [JarLoader] Loading library jackson-module-kotlin
[08:27:05 INFO]: [JarLoader] Loading library kotlin-reflect
[08:27:05 INFO]: [JarLoader] Loading library gson
[08:27:05 INFO]: [JarLoader] Loading library kotlin-stdlib-jdk8
[08:27:05 INFO]: [JarLoader] Loading library kotlin-stdlib
[08:27:05 INFO]: [JarLoader] Loading library kotlin-stdlib-common
[08:27:05 INFO]: [JarLoader] Loading library kotlin-stdlib-jdk7
[08:27:05 ERROR]: Error occurred while enabling JarLoader v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/javalin/Javalin
	at com.itsrainingplex.jarloader.JarLoader.onEnable(JarLoader.java:24) ~[JarLoader-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.javalin.Javalin
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 13 more
[08:27:05 INFO]: [JarLoader] Disabling JarLoader v1.0.0
[08:27:05 INFO]: Running delayed init tasks
[08:27:05 INFO]: Done (15.138s)! For help, type "help"
[08:27:05 INFO]: Timings Reset```
